ombre:  Construir

en: 
  empujar: 
    ramas: 
      -  principal


trabajos: 
  compilación: 
    nombre:  compilación en ejecución 
    :  ubuntu-latest 
    permisos:  leer todos 
    los pasos: 
      -  usos:  acciones/checkout@v2 
        con: 
          búsqueda de profundidad:  0   # Los clones superficiales deben deshabilitarse para una mejor relevancia del análisis 
      -  usos :  sonarsource/sonarqube-scan-action@master 
        env: 
          SONAR_TOKEN:  ${{  secrets.SONAR_TOKEN  }} 
          SONAR_HOST_URL:  ${{  secrets.SONAR_HOST_URL  }} 
      # Si desea suspender su trabajo cuando el Quality Gate esté en rojo, descomente el 
      # siguientes líneas. Normalmente, esto se utilizaría para fallar en una implementación.
      # - usos: sonarsource/sonarqube-quality-gate-action@master 
      # tiempo de espera-minutos: 5 
      # env: 
      # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
